name: Build and Translate Artifacts

on:
  workflow_dispatch:
    inputs:
      language:
        description: "Target language for translation"
        required: true
        default: "en"
        type: choice
        options:
          - es
          - fr
          - de
          - it
          - pt

permissions:
  contents: write

jobs:
  build-translate-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Translate to target language
        run: npm run translate -- ${{ github.event.inputs.language }}

      - name: Get Zip name
        id: get_zip_name
        run: |
          ZIPNAME=$(node scripts/zipname.js)
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_OUTPUT

      - name: Create zip artifact
        run: npm run zipper

      - name: Get latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          name: Release ${{ steps.get_latest_tag.outputs.LATEST_TAG }} Translations
          # body: ${{ steps.generate_changelog.outputs.result }}
          files: ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
